/* This file was generated by the Hex-Rays decompiler version 9.3.0.260213.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (*init_proc())(void);
// void free(void *ptr);
// int puts(const char *s);
// ssize_t write(int fd, const void *buf, size_t n);
// int fclose(FILE *stream);
// int printf(const char *format, ...);
// ssize_t read(int fd, void *buf, size_t nbytes);
// __int64 __isoc23_scanf(const char *, ...); weak
// int putc(int c, FILE *stream);
// void *malloc(size_t size);
// int fflush(FILE *stream);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// FILE *fopen(const char *filename, const char *modes);
// void __noreturn exit(int status);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// int getc(FILE *stream);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
void *sub_1160();
int sub_1229();
int sub_1283();
__int64 __fastcall sub_12E5(_QWORD, _QWORD); // weak
int sub_1343();
int sub_141F();
int sub_14D1();
int sub_154E();
void sub_15BA();
void __fastcall __noreturn main(__int64 a1, char **a2, char **a3);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// __int64 ITM_deregisterTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN *off_3FD8 = &_libc_start_main; // weak
__int64 (*off_3FE8)(void) = &_gmon_start__; // weak
_UNKNOWN unk_4010; // weak
FILE *stdout; // idb
FILE *stdin; // idb
FILE *stderr; // idb
_QWORD qword_4060[4]; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (*init_proc())(void)
{
  __int64 (*result)(void); // rax

  result = off_3FE8;
  if ( off_3FE8 )
    return (__int64 (*)(void))off_3FE8();
  return result;
}
// 3FE8: using guessed type __int64 (*off_3FE8)(void);

//----- (0000000000001130) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  ((void (__fastcall *)(int (*)(int, char **, char **), int, char **, void (*)(), void (*)(), void (*)(), void *))off_3FD8)(
    (int (*)(int, char **, char **))main,
    v4,
    &retaddr,
    nullptr,
    nullptr,
    a3,
    &v5);
  __halt();
}
// 113A: positive sp value 8 has been found
// 3FD8: invalid function type '?' has been ignored
// 1141: variable 'v3' is possibly undefined
// 3FD8: using guessed type _UNKNOWN *off_3FD8;

//----- (0000000000001160) ----------------------------------------------------
void *sub_1160()
{
  return &unk_4010;
}
// 4110: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000001229) ----------------------------------------------------
int sub_1229()
{
  setvbuf(stdin, nullptr, 2, 0);
  setvbuf(stdout, nullptr, 2, 0);
  return setvbuf(stderr, nullptr, 2, 0);
}

//----- (0000000000001283) ----------------------------------------------------
int sub_1283()
{
  puts("1. register");
  puts("2. show");
  puts("3. login");
  puts("4. update");
  puts("5. delete");
  puts("6. exit");
  return printf("> ");
}

//----- (00000000000012E5) ----------------------------------------------------
__int64 sub_12E5()
{
  unsigned int v1; // [rsp+4h] [rbp-14h] BYREF
  unsigned __int64 v2; // [rsp+8h] [rbp-10h]

  v2 = __readfsqword(0x28u);
  if ( (unsigned int)__isoc23_scanf("%d", &v1) != 1 )
    exit(1);
  getc(stdin);
  return v1;
}
// 10A0: using guessed type __int64 __isoc23_scanf(const char *, ...);
// 12E5: using guessed type __int64 sub_12E5();

//----- (0000000000001343) ----------------------------------------------------
int sub_1343()
{
  __int64 v0; // rbx
  _OWORD *v2; // rbp

  v0 = 0;
  while ( qword_4060[v0] )
  {
    if ( ++v0 == 4 )
      return puts("full");
  }
  v2 = malloc(0x48u);
  *v2 = 0;
  v2[1] = 0;
  v2[2] = 0;
  v2[3] = 0;
  *((_QWORD *)v2 + 8) = 0;
  *((_QWORD *)v2 + 8) = fopen("/dev/null", "a");
  printf("username: ");
  read(0, v2, 0x40u);
  qword_4060[(int)v0] = v2;
  return printf("registered at slot %d\n", v0);
}
// 4060: using guessed type _QWORD qword_4060[4];

//----- (000000000000141F) ----------------------------------------------------
int sub_141F()
{
  unsigned int v0; // eax
  unsigned int v1; // ebx

  printf("slot: ");
  v0 = sub_12E5();
  if ( v0 > 3 )
    return puts("invalid");
  v1 = v0;
  if ( !qword_4060[v0] )
    return puts("invalid");
  printf("username: ");
  printf((const char *)qword_4060[v1]);
  putc(10, stdout);
  return write(1, (const void *)qword_4060[v1], 0x48u);
}
// 12E5: using guessed type __int64 sub_12E5(void);
// 4060: using guessed type _QWORD qword_4060[4];

//----- (00000000000014D1) ----------------------------------------------------
int sub_14D1()
{
  unsigned int v0; // eax
  unsigned int v1; // ebx
  __int64 v2; // rax

  printf("slot: ");
  v0 = sub_12E5();
  if ( v0 > 3 )
    return puts("invalid");
  v1 = v0;
  v2 = qword_4060[v0];
  if ( !v2 )
    return puts("invalid");
  fwrite("login\n", 1u, 6u, *(FILE **)(v2 + 64));
  fflush(*(FILE **)(qword_4060[v1] + 64LL));
  return puts("welcome!");
}
// 12E5: using guessed type __int64 sub_12E5(void);
// 4060: using guessed type _QWORD qword_4060[4];

//----- (000000000000154E) ----------------------------------------------------
int sub_154E()
{
  unsigned int v0; // eax
  unsigned int v1; // ebx

  printf("slot: ");
  v0 = sub_12E5();
  if ( v0 > 3 )
    return puts("invalid");
  v1 = v0;
  if ( !qword_4060[v0] )
    return puts("invalid");
  printf("new username: ");
  return read(0, (void *)qword_4060[v1], 0x200u);
}
// 12E5: using guessed type __int64 sub_12E5(void);
// 4060: using guessed type _QWORD qword_4060[4];

//----- (00000000000015BA) ----------------------------------------------------
void sub_15BA()
{
  unsigned int v0; // eax
  unsigned int v1; // ebx
  __int64 v2; // rax

  printf("slot: ");
  v0 = sub_12E5();
  if ( v0 <= 3 && (v1 = v0, (v2 = qword_4060[v0]) != 0) )
  {
    fclose(*(FILE **)(v2 + 64));
    free((void *)qword_4060[v1]);
    qword_4060[v1] = 0;
  }
  else
  {
    puts("invalid");
  }
}
// 12E5: using guessed type __int64 sub_12E5(void);
// 4060: using guessed type _QWORD qword_4060[4];

//----- (0000000000001641) ----------------------------------------------------
void __fastcall __noreturn main(__int64 a1, char **a2, char **a3)
{
  sub_1229();
  while ( 1 )
  {
    sub_1283();
    switch ( sub_12E5(a1, a2) )
    {
      case 1LL:
        sub_1343();
        break;
      case 2LL:
        sub_141F();
        break;
      case 3LL:
        sub_14D1();
        break;
      case 4LL:
        sub_154E();
        break;
      case 5LL:
        sub_15BA();
        break;
      case 6LL:
        exit(0);
      default:
        continue;
    }
  }
}
// 12E5: using guessed type __int64 __fastcall sub_12E5(_QWORD, _QWORD);

//----- (0000000000001698) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=49 queued=13 decompiled=13 lumina nreq=0 worse=0 better=0
// ALL OK, 13 function(s) have been successfully decompiled
